/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MedicoControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoCanales
 */
public class DlgeditarMedico extends javax.swing.JDialog {
    
    MedicoControlador controlador = new MedicoControlador();

    /**
     * Creates new form DlgeditarMedico
     * @param parent
     */
    public DlgeditarMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMedico = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        txtNombreMedico = new javax.swing.JTextField();
        lblApellidoMedico = new javax.swing.JLabel();
        txtApellidoMedico = new javax.swing.JTextField();
        lblDireccionMedico = new javax.swing.JLabel();
        txtDireccionMedico = new javax.swing.JTextField();
        lblFechaNacimientoMedico = new javax.swing.JLabel();
        txtFechaNacimientoMedico = new javax.swing.JTextField();
        lblDniMedico = new javax.swing.JLabel();
        txtDniMedico = new javax.swing.JTextField();
        lblCelularMedico = new javax.swing.JLabel();
        txtCelularMedico = new javax.swing.JTextField();
        lblEspecialidadMedico = new javax.swing.JLabel();
        txtEspecialidadMedico = new javax.swing.JTextField();
        lblSexoMedico = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lbleditaridmedico = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloMedico.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTituloMedico.setText("Editar Médico");

        lblNombreMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblNombreMedico.setText("Nombre:");

        txtNombreMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblApellidoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblApellidoMedico.setText("Apellido:");

        txtApellidoMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblDireccionMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDireccionMedico.setText("Dirección:");

        txtDireccionMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblFechaNacimientoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblFechaNacimientoMedico.setText("Fecha de Nacimiento:");

        txtFechaNacimientoMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblDniMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDniMedico.setText("Nº de Dni:");

        txtDniMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblCelularMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCelularMedico.setText("Nº de Teléfono:");

        txtCelularMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblEspecialidadMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblEspecialidadMedico.setText("Especialidad:");

        txtEspecialidadMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblSexoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblSexoMedico.setText("Género:");

        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lbleditaridmedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbleditaridmedico.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCancelar)
                            .addGap(18, 18, 18)
                            .addComponent(btnGuardar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEspecialidadMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEspecialidadMedico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCelularMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDireccionMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccionMedico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblApellidoMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellidoMedico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloMedico)
                                .addGap(71, 71, 71)
                                .addComponent(lbleditaridmedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDniMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaNacimientoMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaNacimientoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSexoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloMedico)
                    .addComponent(lbleditaridmedico)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMedico)
                    .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoMedico)
                    .addComponent(txtApellidoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionMedico)
                    .addComponent(txtDireccionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoMedico)
                    .addComponent(txtFechaNacimientoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniMedico)
                    .addComponent(txtDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelularMedico)
                    .addComponent(txtCelularMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidadMedico)
                    .addComponent(txtEspecialidadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexoMedico)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed

    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String genero = "";
        if(cbxGenero.getSelectedItem().equals("Masculino")){
            genero = "M";
        }else{
            genero = "F";
        }

        System.out.println("Genero: "+ genero);
        String nombre = txtNombreMedico.getText();
        String apellido = txtApellidoMedico.getText();
        String direc = txtDireccionMedico.getText();
        String fecha_nac = txtFechaNacimientoMedico.getText();
        String dni = txtDniMedico.getText();
        String cell = txtCelularMedico.getText();
        String espec = txtEspecialidadMedico.getText();
        boolean esCorrecto = controlador.agregarMedico(nombre, apellido, direc, fecha_nac, dni, cell, espec, genero);
        if (esCorrecto) {
            JOptionPane.showMessageDialog(null, "Se agregó el Paciente correctamente", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Se agregó el medico correctamente", "Mensaje del sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgeditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgeditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgeditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgeditarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgeditarMedico dialog = new DlgeditarMedico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblApellidoMedico;
    private javax.swing.JLabel lblCelularMedico;
    private javax.swing.JLabel lblDireccionMedico;
    private javax.swing.JLabel lblDniMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblFechaNacimientoMedico;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblSexoMedico;
    private javax.swing.JLabel lblTituloMedico;
    private javax.swing.JLabel lbleditaridmedico;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtCelularMedico;
    private javax.swing.JTextField txtDireccionMedico;
    private javax.swing.JTextField txtDniMedico;
    private javax.swing.JTextField txtEspecialidadMedico;
    private javax.swing.JTextField txtFechaNacimientoMedico;
    private javax.swing.JTextField txtNombreMedico;
    // End of variables declaration//GEN-END:variables
}
