/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.MedicoControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoCanales
 */
public class DlgeditarMedico extends javax.swing.JDialog {
    
    MedicoControlador controlador = new MedicoControlador();
    String id;
    String nombre;
    String apellido;
    String direccion;
    String fecha_nac;
    String dni;
    String celular;
    String especialidad;
    String sexo;

    /**
     * Creates new form DlgeditarMedico
     * @param parent
     * @param modal
     */
    public DlgeditarMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        editarComboGenero();
    }
    
    public void editarComboGenero(){
        cbxEditargenero.addItem("Masculino");
        cbxEditargenero.addItem("Femenino");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMedico = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        txtNombreMedico = new javax.swing.JTextField();
        lblApellidoMedico = new javax.swing.JLabel();
        txtApellidoMedico = new javax.swing.JTextField();
        lblDireccionMedico = new javax.swing.JLabel();
        txtDireccionMedico = new javax.swing.JTextField();
        lblFechaNacimientoMedico = new javax.swing.JLabel();
        txtFechaNacimientoMedico = new javax.swing.JTextField();
        lblDniMedico = new javax.swing.JLabel();
        txtDniMedico = new javax.swing.JTextField();
        lblCelularMedico = new javax.swing.JLabel();
        txtCelularMedico = new javax.swing.JTextField();
        lblEspecialidadMedico = new javax.swing.JLabel();
        txtEspecialidadMedico = new javax.swing.JTextField();
        lblSexoMedico = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        lbleditaridmedico = new javax.swing.JLabel();
        txtIdMedico = new javax.swing.JTextField();
        btnActualizarMedico = new javax.swing.JButton();
        cbxEditargenero = new javax.swing.JComboBox<>();
        btnInactivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTituloMedico.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblTituloMedico.setText("Editar Médico");

        lblNombreMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblNombreMedico.setText("Nombre:");

        txtNombreMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblApellidoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblApellidoMedico.setText("Apellido:");

        txtApellidoMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblDireccionMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDireccionMedico.setText("Dirección:");

        txtDireccionMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblFechaNacimientoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblFechaNacimientoMedico.setText("Fecha de Nacimiento:");

        txtFechaNacimientoMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblDniMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDniMedico.setText("Nº de Dni:");

        txtDniMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblCelularMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCelularMedico.setText("Nº de Teléfono:");

        txtCelularMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblEspecialidadMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblEspecialidadMedico.setText("Especialidad:");

        txtEspecialidadMedico.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N

        lblSexoMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblSexoMedico.setText("Género:");

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbleditaridmedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbleditaridmedico.setText("ID:");

        btnActualizarMedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnActualizarMedico.setText("Actualizar");
        btnActualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMedicoActionPerformed(evt);
            }
        });

        cbxEditargenero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnInactivar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnInactivar.setText("Inactivar");
        btnInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblEspecialidadMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEspecialidadMedico))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCelularMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDireccionMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionMedico))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblApellidoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoMedico))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNombreMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTituloMedico)
                        .addGap(71, 71, 71)
                        .addComponent(lbleditaridmedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDniMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblFechaNacimientoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNacimientoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInactivar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarMedico)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSexoMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEditargenero, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloMedico)
                    .addComponent(lbleditaridmedico)
                    .addComponent(txtIdMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMedico)
                    .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoMedico)
                    .addComponent(txtApellidoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionMedico)
                    .addComponent(txtDireccionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoMedico)
                    .addComponent(txtFechaNacimientoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniMedico)
                    .addComponent(txtDniMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelularMedico)
                    .addComponent(txtCelularMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecialidadMedico)
                    .addComponent(txtEspecialidadMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSexoMedico)
                    .addComponent(cbxEditargenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnActualizarMedico)
                    .addComponent(btnInactivar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMedicoActionPerformed
        String genero = "";
        if(cbxEditargenero.getSelectedItem().equals("Masculino")){
            genero = "M";
        }else{
            genero = "F";
        }
        System.out.println("Genero: "+ genero);
        String nombre = txtNombreMedico.getText();
        String apellido = txtApellidoMedico.getText();
        String direc = txtDireccionMedico.getText();
        String fecha_nac = txtFechaNacimientoMedico.getText();
        String dni = txtDniMedico.getText();
        String cell = txtCelularMedico.getText();
        String espec = txtEspecialidadMedico.getText();
        boolean esCorrecto = controlador.actualizarMedico(0, nombre, apellido, direc, fecha_nac, dni, cell, espec, genero);
        if (esCorrecto) {
            JOptionPane.showMessageDialog(null, "Se agregó el Médico correctamente", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se agregó el Médico correctamente", "Mensaje del sistema", JOptionPane.ERROR_MESSAGE);
        }
        String seleccion = (String)cbxEditargenero.getSelectedItem();
        int indice = cbxEditargenero.getSelectedIndex();

        System.out.println("Selección: "+ seleccion);
        System.out.println("Indice: "+ indice);
    }//GEN-LAST:event_btnActualizarMedicoActionPerformed

    private void btnInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarActionPerformed
        int id = Integer.parseInt(txtIdMedico.getText());
        boolean esCorrecto = controlador.inactivarMedico(id);
        if(esCorrecto){
            JOptionPane.showMessageDialog(null, "Se inactivó este Médico", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Ocurrió un error al inactivar Médico", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInactivarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtIdMedico.setText(id);
        txtNombreMedico.setText(nombre);
        txtApellidoMedico.setText(apellido);
        txtDireccionMedico.setText(direccion);
        txtFechaNacimientoMedico.setText(fecha_nac);
        txtDniMedico.setText(dni);
        txtCelularMedico.setText(celular);
        txtEspecialidadMedico.setText(especialidad);
        
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarMedico;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInactivar;
    private javax.swing.JComboBox<String> cbxEditargenero;
    private javax.swing.JLabel lblApellidoMedico;
    private javax.swing.JLabel lblCelularMedico;
    private javax.swing.JLabel lblDireccionMedico;
    private javax.swing.JLabel lblDniMedico;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblFechaNacimientoMedico;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblSexoMedico;
    private javax.swing.JLabel lblTituloMedico;
    private javax.swing.JLabel lbleditaridmedico;
    private javax.swing.JTextField txtApellidoMedico;
    private javax.swing.JTextField txtCelularMedico;
    private javax.swing.JTextField txtDireccionMedico;
    private javax.swing.JTextField txtDniMedico;
    private javax.swing.JTextField txtEspecialidadMedico;
    private javax.swing.JTextField txtFechaNacimientoMedico;
    private javax.swing.JTextField txtIdMedico;
    private javax.swing.JTextField txtNombreMedico;
    // End of variables declaration//GEN-END:variables
}
