/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author FernandoCanales
 */
public class DlgeditarConsulta extends javax.swing.JDialog {

    ConsultaControlador controlador = new ConsultaControlador();
    public String idConsulta;
    public String idMedico;
    public String idPaciente;
    public String fechaConsulta;
    public String descripcion;

    /**
     * Creates new form DlgeditarConsulta
     */
    public DlgeditarConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void cargarDatos() {
        txtIdConsulta.setText(idConsulta);
        txtidmedico.setText(idMedico);
        txtidpaciente.setText(idPaciente);
        txtfechaconsulta.setText(fechaConsulta);
        txtDescripcion.setText(descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloeditarconsulta = new javax.swing.JLabel();
        lblidconsulta = new javax.swing.JLabel();
        txtIdConsulta = new javax.swing.JTextField();
        lblidmedico = new javax.swing.JLabel();
        txtidmedico = new javax.swing.JTextField();
        lblidpaciente = new javax.swing.JLabel();
        txtidpaciente = new javax.swing.JTextField();
        lblfechaconsulta = new javax.swing.JLabel();
        txtfechaconsulta = new javax.swing.JTextField();
        lbldescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTituloeditarconsulta.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblTituloeditarconsulta.setText("Editar Consulta");
        lblTituloeditarconsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloeditarconsultaMouseClicked(evt);
            }
        });

        lblidconsulta.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblidconsulta.setText("ID:");

        txtIdConsulta.setEditable(false);
        txtIdConsulta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtIdConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdConsultaActionPerformed(evt);
            }
        });

        lblidmedico.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblidmedico.setText("ID Médico:");

        txtidmedico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblidpaciente.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblidpaciente.setText("ID Paciente:");

        txtidpaciente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblfechaconsulta.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblfechaconsulta.setText("Fecha de la Consulta:");

        txtfechaconsulta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtfechaconsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaconsultaKeyTyped(evt);
            }
        });

        lbldescripcion.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lbldescripcion.setText("Descripción:");

        txtDescripcion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldescripcion)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescripcion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblfechaconsulta)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfechaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblidpaciente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtidpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblidmedico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtidmedico, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTituloeditarconsulta)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblidconsulta)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloeditarconsulta)
                    .addComponent(lblidconsulta)
                    .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidmedico)
                    .addComponent(txtidmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidpaciente)
                    .addComponent(txtidpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfechaconsulta)
                    .addComponent(txtfechaconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnActualizar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarDatos();
    }//GEN-LAST:event_formWindowOpened

    private void txtIdConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdConsultaActionPerformed

    }//GEN-LAST:event_txtIdConsultaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String idConsulta = txtIdConsulta.getText();
        String idMedico = txtidmedico.getText();
        String idPaciente = txtidpaciente.getText();
        String fechaConsulta = txtfechaconsulta.getText();
        String descripcion = txtDescripcion.getText();
        boolean esCorrecto = controlador.actualizarConsulta(idConsulta, idMedico, idPaciente, fechaConsulta, descripcion);
        if (esCorrecto) {
            JOptionPane.showMessageDialog(null, "Se actualizó la consulta correctamente", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al actualizar el médico", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void lblTituloeditarconsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloeditarconsultaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTituloeditarconsultaMouseClicked

    private void txtfechaconsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaconsultaKeyTyped
        
    }//GEN-LAST:event_txtfechaconsultaKeyTyped

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        
    }//GEN-LAST:event_txtDescripcionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblTituloeditarconsulta;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblfechaconsulta;
    private javax.swing.JLabel lblidconsulta;
    private javax.swing.JLabel lblidmedico;
    private javax.swing.JLabel lblidpaciente;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdConsulta;
    private javax.swing.JTextField txtfechaconsulta;
    private javax.swing.JTextField txtidmedico;
    private javax.swing.JTextField txtidpaciente;
    // End of variables declaration//GEN-END:variables
}
