/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaControlador;
import java.awt.Frame;

/**
 *
 * @author FernandoCanales
 */
public class DlgVistaConsulta extends javax.swing.JDialog {
    
    Frame parentFrame;
    ConsultaControlador controlador = new ConsultaControlador();

    /**
     * Creates new form DlgVistaConsulta
     */
    public DlgVistaConsulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        initComponents();
        this.setLocationRelativeTo(null);
        cargarListaConsulta();
    }
    
    public void cargarListaConsulta(){
        try {
            tblConsulta.setModel(controlador.listarConsulta());
        } catch (Exception e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloConsulta = new javax.swing.JLabel();
        srcConsulta = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnNuevaConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloConsulta.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblTituloConsulta.setText("Consultas");

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultaMouseClicked(evt);
            }
        });
        srcConsulta.setViewportView(tblConsulta);

        btnNuevaConsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNuevaConsulta.setText("Nueva Consulta");
        btnNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevaConsulta))
                    .addComponent(srcConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblTituloConsulta)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevaConsulta)
                        .addGap(18, 18, 18)))
                .addComponent(srcConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaConsultaActionPerformed
        DlgNuevaConsulta dlgnuevaconsulta = new DlgNuevaConsulta(parentFrame, true);
        dlgnuevaconsulta.setVisible(true);
        cargarListaConsulta();
    }//GEN-LAST:event_btnNuevaConsultaActionPerformed
    
    //Método para abrir la ventana editar consulta
    private void tblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMouseClicked
        int filaSeleccionada = tblConsulta.getSelectedRow();
        
        DlgeditarConsulta dlgeditarconsulta = new DlgeditarConsulta(parentFrame, true);
        dlgeditarconsulta.idConsulta = tblConsulta.getModel().getValueAt(filaSeleccionada, 0).toString();
        dlgeditarconsulta.idMedico = tblConsulta.getModel().getValueAt(filaSeleccionada, 1).toString();
        dlgeditarconsulta.idPaciente = tblConsulta.getModel().getValueAt(filaSeleccionada, 2).toString();
        dlgeditarconsulta.fechaConsulta = tblConsulta.getModel().getValueAt(filaSeleccionada, 3).toString();
        dlgeditarconsulta.descripcion = tblConsulta.getModel().getValueAt(filaSeleccionada, 4).toString();
        
        dlgeditarconsulta.setVisible(true);
        cargarListaConsulta();
    }//GEN-LAST:event_tblConsultaMouseClicked
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevaConsulta;
    private javax.swing.JLabel lblTituloConsulta;
    private javax.swing.JScrollPane srcConsulta;
    private javax.swing.JTable tblConsulta;
    // End of variables declaration//GEN-END:variables
}
